tinyMCE.addI18n('en.advanced',{
    "underline_desc":"Souligné (Ctrl+U)",
    "italic_desc":"Italique (Ctrl+I)",
    "bold_desc":"Gras (Ctrl+B)",
    dd:"Definition Description",
    dt:"Definition Term ",
    samp:"Code Sample",
    code:"Code",
    blockquote:"Citation",
    h6:"Heading 6",
    h5:"Heading 5",
    h4:"Heading 4",
    h3:"<span style=\"font-weight:700;color:#3F3F38;margin-left: 10px; color: #3F3F38;\">Titre de sous-partie</span>",
    h2:"<span style=\"font-weight:700;color:#E8A22B;\">Titre de partie</span>",
    h1:"Titre",
    pre:"Preformatted",
    address:"Address",
    div:"DIV",
    paragraph:"Paragraphe",
    block:"Titre",
    fontdefault:"Font Family",
    "font_size":"Font Size",
    "style_select":"Styles",
    "anchor_delta_height":"",
    "anchor_delta_width":"",
    "charmap_delta_height":"",
    "charmap_delta_width":"",
    "colorpicker_delta_height":"",
    "colorpicker_delta_width":"",
    "link_delta_height":"",
    "link_delta_width":"",
    "image_delta_height":"",
    "image_delta_width":"",
    "more_colors":"More Colors...",
    "toolbar_focus":"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
    newdocument:"Are you sure you want clear all contents?",
    path:"Path",
    "clipboard_msg":"Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?",
    "blockquote_desc":"Citation",
    "help_desc":"Aide",
    "newdocument_desc":"New Document",
    "image_props_desc":"Image Properties",
    "paste_desc":"Coller (Ctrl+V)",
    "copy_desc":"Copier (Ctrl+C)",
    "cut_desc":"Couper (Ctrl+X)",
    "anchor_desc":"Ajouter/modifier un lien",
    "visualaid_desc":"show/Hide Guidelines/Invisible Elements",
    "charmap_desc":"Insert Special Character",
    "backcolor_desc":"Select Background Color",
    "forecolor_desc":"Changer la couleur du texte",
    "custom1_desc":"Your Custom Description Here",
    "removeformat_desc":"Remove Formatting",
    "hr_desc":"Insert Horizontal Line",
    "sup_desc":"Mettre en puissance",
    "sub_desc":"Mettre en indice",
    "code_desc":"Editer le code HTML",
    "cleanup_desc":"Cleanup Messy Code",
    "image_desc":"Insert/Edit Image",
    "unlink_desc":"Supprimer le lien",
    "link_desc":"Insert/Edit Link",
    "redo_desc":"Répéter (Ctrl+Y)",
    "undo_desc":"Annuler (Ctrl+Z)",
    "indent_desc":"Increase Indent",
    "outdent_desc":"Decrease Indent",
    "numlist_desc":"Ajouter/Supprimer une liste numérotée",
    "bullist_desc":"Ajouter/Supprimer une liste",
    "justifyfull_desc":"Justifier",
    "justifyright_desc":"Aligner à droite",
    "justifycenter_desc":"Centrer",
    "justifyleft_desc":"Aligner à gauche",
    "striketrough_desc":"Barré",
    "help_shortcut":"Press ALT-F10 for toolbar. Press ALT-0 for help",
    "rich_text_area":"Rich Text Area",
    "shortcuts_desc":"Accessability Help",
    toolbar:"Toolbar"
});